apiVersion: v1
data:
  daemon-config.json: "{\r\n    \"anchor\": {},\r\n    \"http-api\": {\r\n        \"cors-allowed-origins\":
    [\r\n            \"${CERAMIC_CORS_ALLOWED_ORIGINS}\"\r\n        ],\r\n        \"admin-dids\":
    [\r\n            \"${CERAMIC_ADMIN_DID}\"\r\n        ]\r\n    },\r\n    \"ipfs\":
    {\r\n        \"mode\": \"remote\",\r\n        \"host\": \"${CERAMIC_IPFS_HOST}\"\r\n
    \   },\r\n    \"logger\": {\r\n        \"log-level\": ${CERAMIC_LOG_LEVEL},\r\n
    \       \"log-to-files\": false\r\n    },\r\n    \"metrics\": {\r\n        \"metrics-exporter-enabled\":
    false,\r\n        \"prometheus-exporter-enabled\": true,\r\n        \"prometheus-exporter-port\":
    9464\r\n    },\r\n    \"network\": {\r\n        \"name\": \"${CERAMIC_NETWORK}\"\r\n
    \   },\r\n    \"node\": {},\r\n    \"state-store\": {\r\n        \"mode\": \"fs\",\r\n
    \       \"local-directory\": \"${CERAMIC_STATE_STORE_PATH}\"\r\n    },\r\n    \"indexing\":
    {\r\n        \"db\": \"postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}\",\r\n
    \       \"allow-queries-before-historical-sync\": true\r\n    }\r\n}"
  js-ceramic-init.sh: |-
    #!/bin/bash

    set -eo pipefail

    export MY_POD_INDEX=$(echo $MY_POD_NAME | grep -o '[0-9]\+$')
    export CERAMIC_IPFS_HOST=http://ceramic-one-${MY_POD_INDEX}:5101
    export CERAMIC_ADMIN_DID=$(composedb did:from-private-key ${CERAMIC_ADMIN_PRIVATE_KEY})

    CERAMIC_ADMIN_DID=$CERAMIC_ADMIN_DID envsubst < /js-ceramic-init/daemon-config.json > /config/daemon-config.json
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"daemon-config.json":"{\r\n    \"anchor\": {},\r\n    \"http-api\": {\r\n        \"cors-allowed-origins\": [\r\n            \"${CERAMIC_CORS_ALLOWED_ORIGINS}\"\r\n        ],\r\n        \"admin-dids\": [\r\n            \"${CERAMIC_ADMIN_DID}\"\r\n        ]\r\n    },\r\n    \"ipfs\": {\r\n        \"mode\": \"remote\",\r\n        \"host\": \"${CERAMIC_IPFS_HOST}\"\r\n    },\r\n    \"logger\": {\r\n        \"log-level\": ${CERAMIC_LOG_LEVEL},\r\n        \"log-to-files\": false\r\n    },\r\n    \"metrics\": {\r\n        \"metrics-exporter-enabled\": false,\r\n        \"prometheus-exporter-enabled\": true,\r\n        \"prometheus-exporter-port\": 9464\r\n    },\r\n    \"network\": {\r\n        \"name\": \"${CERAMIC_NETWORK}\"\r\n    },\r\n    \"node\": {},\r\n    \"state-store\": {\r\n        \"mode\": \"fs\",\r\n        \"local-directory\": \"${CERAMIC_STATE_STORE_PATH}\"\r\n    },\r\n    \"indexing\": {\r\n        \"db\": \"postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}\",\r\n        \"allow-queries-before-historical-sync\": true\r\n    }\r\n}","js-ceramic-init.sh":"#!/bin/bash\n\nset -eo pipefail\n\nexport MY_POD_INDEX=$(echo $MY_POD_NAME | grep -o '[0-9]\\+$')\nexport CERAMIC_IPFS_HOST=http://ceramic-one-${MY_POD_INDEX}:5101\nexport CERAMIC_ADMIN_DID=$(composedb did:from-private-key ${CERAMIC_ADMIN_PRIVATE_KEY})\n\nCERAMIC_ADMIN_DID=$CERAMIC_ADMIN_DID envsubst \u003c /js-ceramic-init/daemon-config.json \u003e /config/daemon-config.json"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"js-ceramic-init-mcbg7bk4cg","namespace":"ceramic-one-dev"}}
  creationTimestamp: "2024-09-20T15:26:10Z"
  name: js-ceramic-init-mcbg7bk4cg
  namespace: ceramic-one-dev
  resourceVersion: "49176925"
  uid: 5b3630c1-8c4e-4764-ad16-adbd5aded9c5
