/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation CreateZucityAnnouncementMutation(\n    $input: CreateZucityAnnouncementInput!\n  ) {\n    createZucityAnnouncement(input: $input) {\n      document {\n        id\n        title\n        description\n        createdAt\n        updatedAt\n        sourceId\n        spaceId\n        eventId\n        space {\n          id\n          name\n        }\n        event {\n          id\n          title\n        }\n      }\n    }\n  }\n": typeof types.CreateZucityAnnouncementMutationDocument,
    "\n  mutation UpdateZucityAnnouncementMutation(\n    $input: UpdateZucityAnnouncementInput!\n  ) {\n    updateZucityAnnouncement(input: $input) {\n      document {\n        id\n        title\n        description\n        updatedAt\n      }\n    }\n  }\n": typeof types.UpdateZucityAnnouncementMutationDocument,
    "\n  mutation EnableIndexingZucityAnnouncement(\n    $input: EnableIndexingZucityAnnouncementInput!\n  ) {\n    enableIndexingZucityAnnouncement(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": typeof types.EnableIndexingZucityAnnouncementDocument,
    "\n  query GetSpaceAnnouncements($id: ID!, $first: Int = 100) {\n    node(id: $id) {\n      ... on ZucitySpace {\n        announcements(first: $first) {\n          edges {\n            node {\n              id\n              title\n              tags {\n                tag\n              }\n              description\n              createdAt\n              updatedAt\n              sourceId\n              author {\n                id\n                zucityProfile {\n                  avatar\n                  username\n                }\n              }\n            }\n          }\n          pageInfo {\n            hasNextPage\n            endCursor\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetSpaceAnnouncementsDocument,
    "\n  query GetEventAnnouncements($id: ID!, $first: Int = 100) {\n    node(id: $id) {\n      ... on ZucityEvent {\n        announcements(first: $first) {\n          edges {\n            node {\n              id\n              title\n              tags {\n                tag\n              }\n              description\n              createdAt\n              updatedAt\n              sourceId\n              author {\n                id\n                zucityProfile {\n                  avatar\n                  username\n                }\n              }\n            }\n          }\n          pageInfo {\n            hasNextPage\n            endCursor\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetEventAnnouncementsDocument,
    "\n  query GetDappList($first: Int = 100, $filters: ZucityDappInfoFiltersInput) {\n    zucityDappInfoIndex(first: $first, filters: $filters) {\n      edges {\n        node {\n          id\n          appName\n          tagline\n          developerName\n          description\n          bannerUrl\n          categories\n          devStatus\n          openSource\n          repositoryUrl\n          appUrl\n          websiteUrl\n          docsUrl\n          isInstallable\n          appLogoUrl\n          auditLogUrl\n          isSCApp\n          scAddresses {\n            address\n            chain\n          }\n          profile {\n            author {\n              id\n            }\n            avatar\n            username\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetDappListDocument,
    "\n  mutation CreateZucityDappMutation($input: CreateZucityDappInfoInput!) {\n    createZucityDappInfo(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": typeof types.CreateZucityDappMutationDocument,
    "\n  mutation UpdateZucityDappMutation($input: UpdateZucityDappInfoInput!) {\n    updateZucityDappInfo(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": typeof types.UpdateZucityDappMutationDocument,
    "\n  query GetDappById($id: ID!) {\n    node(id: $id) {\n      ... on ZucityDappInfo {\n        id\n        appName\n        tagline\n        developerName\n        description\n        bannerUrl\n        categories\n        devStatus\n        openSource\n        repositoryUrl\n        appUrl\n        websiteUrl\n        docsUrl\n        isInstallable\n        appLogoUrl\n        auditLogUrl\n        isSCApp\n        scAddresses {\n          address\n          chain\n        }\n        profile {\n          author {\n            id\n          }\n          avatar\n          username\n        }\n      }\n    }\n  }\n": typeof types.GetDappByIdDocument,
    "\n  query GetAllEvents($first: Int) {\n    zucityEventIndex(first: $first) {\n      edges {\n        node {\n          id\n          description\n          profileId\n          tagline\n          customAttributes {\n            tbd\n          }\n          gated\n          superAdmin {\n            id\n          }\n          admins {\n            id\n          }\n          author {\n            id\n          }\n          customLinks {\n            links\n            title\n          }\n          createdAt\n          endTime\n          externalUrl\n          imageUrl\n          members {\n            id\n          }\n          participantCount\n          spaceId\n          startTime\n          status\n          supportChain\n          timezone\n          title\n          tracks\n        }\n      }\n    }\n  }\n": typeof types.GetAllEventsDocument,
    "\n  query GetEventByIds($ids: [ID!]!) {\n    nodes(ids: $ids) {\n      ... on ZucityEvent {\n        id\n        description\n        profileId\n        tagline\n        customAttributes {\n          tbd\n        }\n        gated\n        superAdmin {\n          id\n        }\n        admins {\n          id\n        }\n        author {\n          id\n        }\n        customLinks {\n          links\n          title\n        }\n        createdAt\n        endTime\n        externalUrl\n        imageUrl\n        members {\n          id\n        }\n        participantCount\n        spaceId\n        startTime\n        status\n        supportChain\n        timezone\n        title\n        tracks\n      }\n    }\n  }\n": typeof types.GetEventByIdsDocument,
    "\n  query SearchProfileByExactUsername($username: String!) {\n    zucityProfileIndex(\n      first: 20\n      filters: { where: { username: { equalTo: $username } } }\n    ) {\n      edges {\n        node {\n          id\n          username\n          avatar\n          author {\n            id\n          }\n        }\n      }\n    }\n  }\n": typeof types.SearchProfileByExactUsernameDocument,
    "\n  query GetProfileByDID($did: ID!) {\n    node(id: $did) {\n      ... on CeramicAccount {\n        zucityProfile {\n          id\n          username\n          avatar\n          author {\n            id\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetProfileByDidDocument,
    "\n  mutation CreateProfile($input: SetZucityProfileInput!) {\n    setZucityProfile(input: $input) {\n      document {\n        id\n        username\n      }\n    }\n  }\n": typeof types.CreateProfileDocument,
    "\n  query GetOwnProfile {\n    viewer {\n      zucityProfile {\n        author {\n          id\n        }\n        avatar\n        id\n        username\n      }\n    }\n  }\n": typeof types.GetOwnProfileDocument,
    "\n  query GetUserOwnSpace($did: ID!) {\n    node(id: $did) {\n      ... on CeramicAccount {\n        zucityProfile {\n          id\n          username\n          avatar\n          author {\n            id\n          }\n          spaces(first: 100) {\n            edges {\n              node {\n                id\n                author {\n                  id\n                }\n                avatar\n                banner\n                name\n                description\n                category\n                color\n                profileId\n                customAttributes {\n                  tbd\n                }\n                customLinks {\n                  links\n                  title\n                }\n                owner {\n                  id\n                }\n                socialLinks {\n                  links\n                  title\n                }\n                tagline\n                tags {\n                  tag\n                }\n                createdAt\n                updatedAt\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetUserOwnSpaceDocument,
    "\n  query GetUserOwnEvent($did: ID!) {\n    node(id: $did) {\n      ... on CeramicAccount {\n        zucityProfile {\n          id\n          username\n          avatar\n          events(first: 100) {\n            edges {\n              node {\n                id\n                admins {\n                  id\n                }\n                createdAt\n                author {\n                  id\n                }\n                customAttributes {\n                  tbd\n                }\n                customLinks {\n                  links\n                  title\n                }\n                description\n                endTime\n                externalUrl\n                gated\n                imageUrl\n                members {\n                  id\n                }\n                participantCount\n                minParticipant\n                profileId\n                spaceId\n                startTime\n                status\n                superAdmin {\n                  id\n                }\n                supportChain\n                tagline\n                timezone\n                title\n                tracks\n              }\n            }\n          }\n          author {\n            id\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetUserOwnEventDocument,
    "\n  query GetMembers($source: String, $resourceId: String) {\n    zucityUserRolesIndex(\n      first: 1000\n      filters: {\n        where: {\n          source: { equalTo: $source }\n          resourceId: { equalTo: $resourceId }\n        }\n      }\n    ) {\n      edges {\n        node {\n          roleId\n          customAttributes {\n            tbd\n          }\n          userId {\n            zucityProfile {\n              avatar\n              username\n              author {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetMembersDocument,
    "\n  query GetUserRole($userId: String, $resourceId: String, $resource: String) {\n    zucityUserRolesIndex(\n      first: 1\n      filters: {\n        where: {\n          userId: { equalTo: $userId }\n          resourceId: { equalTo: $resourceId }\n          source: { equalTo: $resource }\n        }\n      }\n    ) {\n      edges {\n        node {\n          id\n          roleId\n          userId {\n            zucityProfile {\n              avatar\n              author {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetUserRoleDocument,
    "\n  mutation CreateZucityUserRoles($input: CreateZucityUserRolesInput!) {\n    createZucityUserRoles(input: $input) {\n      document {\n        userId {\n          id\n        }\n        created_at\n        updated_at\n        resourceId\n        source\n        roleId\n      }\n    }\n  }\n": typeof types.CreateZucityUserRolesDocument,
    "\n  mutation enableIndexingZucityUserRoles(\n    $input: EnableIndexingZucityUserRolesInput!\n  ) {\n    enableIndexingZucityUserRoles(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": typeof types.EnableIndexingZucityUserRolesDocument,
    "\n  mutation UpdateZucityUserRoles($input: UpdateZucityUserRolesInput!) {\n    updateZucityUserRoles(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": typeof types.UpdateZucityUserRolesDocument,
    "\n  query GetUserRoles($userId: String) {\n    zucityUserRolesIndex(\n      first: 1000\n      filters: { where: { userId: { equalTo: $userId } } }\n    ) {\n      edges {\n        node {\n          id\n          roleId\n          resourceId\n          source\n          userId {\n            id\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetUserRolesDocument,
    "\n  query GetSpace($id: ID!) {\n    node(id: $id) {\n      ... on ZucitySpace {\n        id\n        avatar\n        banner\n        description\n        name\n        profileId\n        tagline\n        category\n        color\n        createdAt\n        updatedAt\n        gated\n        tags {\n          tag\n        }\n        customAttributes {\n          tbd\n        }\n        socialLinks {\n          title\n          links\n        }\n        customLinks {\n          title\n          links\n        }\n        owner {\n          id\n          zucityProfile {\n            id\n            avatar\n            author {\n              id\n            }\n            username\n          }\n        }\n        announcements(first: 100) {\n          edges {\n            node {\n              id\n              createdAt\n            }\n          }\n        }\n        installedApps(first: 100) {\n          edges {\n            node {\n              id\n              sourceId\n              spaceId\n              nativeAppName\n              installedAppId\n              createdAt\n              updatedAt\n              installedApp {\n                id\n                appName\n                appType\n                description\n                tagline\n                bannerUrl\n                appUrl\n                openSource\n                devStatus\n                developerName\n                categories\n                appLogoUrl\n              }\n            }\n          }\n        }\n        spaceGating(first: 100) {\n          edges {\n            node {\n              id\n              poapsId {\n                poapId\n              }\n              zuPassInfo {\n                registration\n                eventId\n                eventName\n              }\n              gatingStatus\n              spaceId\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetSpaceDocument,
    "\n  query GetSpaceByIds($ids: [ID!]!) {\n    nodes(ids: $ids) {\n      ... on ZucitySpace {\n        id\n        avatar\n        banner\n        description\n        name\n        profileId\n        tagline\n        category\n        color\n        createdAt\n        updatedAt\n        tags {\n          tag\n        }\n        customAttributes {\n          tbd\n        }\n        socialLinks {\n          title\n          links\n        }\n        customLinks {\n          title\n          links\n        }\n        owner {\n          id\n          zucityProfile {\n            id\n            avatar\n            author {\n              id\n            }\n            username\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetSpaceByIdsDocument,
    "\n  mutation InstallDappToSpace($input: CreateZucityInstalledAppInput!) {\n    createZucityInstalledApp(input: $input) {\n      document {\n        id\n        sourceId\n        spaceId\n        nativeAppName\n        installedAppId\n        installedApp {\n          id\n          appName\n        }\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": typeof types.InstallDappToSpaceDocument,
    "\n  query GetSpaceInstalledApps(\n    $filters: ZucityInstalledAppFiltersInput\n    $first: Int\n    $after: String\n  ) {\n    zucityInstalledAppIndex(filters: $filters, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          sourceId\n          spaceId\n          nativeAppName\n          installedAppId\n          createdAt\n          updatedAt\n          installedApp {\n            id\n            appName\n            appType\n            description\n            tagline\n            bannerUrl\n            appUrl\n            openSource\n            devStatus\n            developerName\n            categories\n            appLogoUrl\n          }\n          space {\n            id\n            name\n          }\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": typeof types.GetSpaceInstalledAppsDocument,
    "\n  mutation UninstallDappFromSpace(\n    $input: EnableIndexingZucityInstalledAppInput!\n  ) {\n    enableIndexingZucityInstalledApp(input: $input) {\n      document {\n        id\n        sourceId\n        spaceId\n        installedAppId\n        installedApp {\n          id\n          appName\n        }\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": typeof types.UninstallDappFromSpaceDocument,
    "\n  mutation createZucitySpaceMutation($input: CreateZucitySpaceInput!) {\n    createZucitySpace(input: $input) {\n      document {\n        id\n        name\n        description\n        profileId\n        avatar\n        banner\n        category\n      }\n    }\n  }\n": typeof types.CreateZucitySpaceMutationDocument,
    "\n  query GetSpaces($first: Int) {\n    zucitySpaceIndex(first: $first) {\n      edges {\n        node {\n          id\n          avatar\n          banner\n          description\n          name\n          profileId\n          tagline\n          category\n          color\n          createdAt\n          updatedAt\n          tags {\n            tag\n          }\n          customAttributes {\n            tbd\n          }\n          socialLinks {\n            title\n            links\n          }\n          customLinks {\n            title\n            links\n          }\n          owner {\n            id\n            zucityProfile {\n              id\n              avatar\n              author {\n                id\n              }\n              username\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetSpacesDocument,
    "\n  query GetSpaceAndEvents(\n    $id: ID!\n    $userRolesFirst: Int = 100\n    $userRolesFilters: ZucityUserRolesFiltersInput\n  ) {\n    node(id: $id) {\n      ... on ZucitySpace {\n        id\n        avatar\n        banner\n        description\n        name\n        profileId\n        tagline\n        category\n        color\n        createdAt\n        updatedAt\n        gated\n        tags {\n          tag\n        }\n        customAttributes {\n          tbd\n        }\n        socialLinks {\n          title\n          links\n        }\n        customLinks {\n          title\n          links\n        }\n        owner {\n          id\n          zucityProfile {\n            id\n            avatar\n            author {\n              id\n            }\n            username\n          }\n        }\n        events(first: 100) {\n          edges {\n            node {\n              createdAt\n              description\n              endTime\n              externalUrl\n              gated\n              id\n              imageUrl\n              maxParticipant\n              meetingUrl\n              minParticipant\n              participantCount\n              profileId\n              spaceId\n              startTime\n              status\n              tagline\n              timezone\n              title\n              space {\n                name\n                avatar\n              }\n            }\n          }\n        }\n        userRoles(filters: $userRolesFilters, first: $userRolesFirst) {\n          edges {\n            node {\n              roleId\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetSpaceAndEventsDocument,
    "\n  query GetSpacesAndMembers(\n    $first: Int\n    $userRolesFirst: Int = 100\n    $userRolesFilters: ZucityUserRolesFiltersInput\n  ) {\n    zucitySpaceIndex(first: $first) {\n      edges {\n        node {\n          id\n          avatar\n          banner\n          description\n          name\n          profileId\n          tagline\n          category\n          color\n          createdAt\n          updatedAt\n          tags {\n            tag\n          }\n          customAttributes {\n            tbd\n          }\n          socialLinks {\n            title\n            links\n          }\n          customLinks {\n            title\n            links\n          }\n          owner {\n            id\n            zucityProfile {\n              id\n              avatar\n              author {\n                id\n              }\n              username\n            }\n          }\n          userRoles(filters: $userRolesFilters, first: $userRolesFirst) {\n            edges {\n              node {\n                roleId\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetSpacesAndMembersDocument,
    "\n  mutation UpdateZucitySpace($input: UpdateZucitySpaceInput!) {\n    updateZucitySpace(input: $input) {\n      document {\n        id\n        name\n        description\n        avatar\n        banner\n        category\n      }\n    }\n  }\n": typeof types.UpdateZucitySpaceDocument,
    "\n  mutation CreateSpaceGatingRule($input: CreateZucitySpaceGatingInput!) {\n    createZucitySpaceGating(input: $input) {\n      document {\n        id\n        spaceId\n        poapsId {\n          poapId\n        }\n        zuPassInfo {\n          registration\n          eventId\n          eventName\n        }\n      }\n    } \n  }\n": typeof types.CreateSpaceGatingRuleDocument,
    "\n  mutation UpdateSpaceGatingRule($input: UpdateZucitySpaceGatingInput!) {\n    updateZucitySpaceGating(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": typeof types.UpdateSpaceGatingRuleDocument,
    "\n  mutation DeleteSpaceGatingRule($input: EnableIndexingZucitySpaceGatingInput!) {\n    enableIndexingZucitySpaceGating(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": typeof types.DeleteSpaceGatingRuleDocument,
};
const documents: Documents = {
    "\n  mutation CreateZucityAnnouncementMutation(\n    $input: CreateZucityAnnouncementInput!\n  ) {\n    createZucityAnnouncement(input: $input) {\n      document {\n        id\n        title\n        description\n        createdAt\n        updatedAt\n        sourceId\n        spaceId\n        eventId\n        space {\n          id\n          name\n        }\n        event {\n          id\n          title\n        }\n      }\n    }\n  }\n": types.CreateZucityAnnouncementMutationDocument,
    "\n  mutation UpdateZucityAnnouncementMutation(\n    $input: UpdateZucityAnnouncementInput!\n  ) {\n    updateZucityAnnouncement(input: $input) {\n      document {\n        id\n        title\n        description\n        updatedAt\n      }\n    }\n  }\n": types.UpdateZucityAnnouncementMutationDocument,
    "\n  mutation EnableIndexingZucityAnnouncement(\n    $input: EnableIndexingZucityAnnouncementInput!\n  ) {\n    enableIndexingZucityAnnouncement(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": types.EnableIndexingZucityAnnouncementDocument,
    "\n  query GetSpaceAnnouncements($id: ID!, $first: Int = 100) {\n    node(id: $id) {\n      ... on ZucitySpace {\n        announcements(first: $first) {\n          edges {\n            node {\n              id\n              title\n              tags {\n                tag\n              }\n              description\n              createdAt\n              updatedAt\n              sourceId\n              author {\n                id\n                zucityProfile {\n                  avatar\n                  username\n                }\n              }\n            }\n          }\n          pageInfo {\n            hasNextPage\n            endCursor\n          }\n        }\n      }\n    }\n  }\n": types.GetSpaceAnnouncementsDocument,
    "\n  query GetEventAnnouncements($id: ID!, $first: Int = 100) {\n    node(id: $id) {\n      ... on ZucityEvent {\n        announcements(first: $first) {\n          edges {\n            node {\n              id\n              title\n              tags {\n                tag\n              }\n              description\n              createdAt\n              updatedAt\n              sourceId\n              author {\n                id\n                zucityProfile {\n                  avatar\n                  username\n                }\n              }\n            }\n          }\n          pageInfo {\n            hasNextPage\n            endCursor\n          }\n        }\n      }\n    }\n  }\n": types.GetEventAnnouncementsDocument,
    "\n  query GetDappList($first: Int = 100, $filters: ZucityDappInfoFiltersInput) {\n    zucityDappInfoIndex(first: $first, filters: $filters) {\n      edges {\n        node {\n          id\n          appName\n          tagline\n          developerName\n          description\n          bannerUrl\n          categories\n          devStatus\n          openSource\n          repositoryUrl\n          appUrl\n          websiteUrl\n          docsUrl\n          isInstallable\n          appLogoUrl\n          auditLogUrl\n          isSCApp\n          scAddresses {\n            address\n            chain\n          }\n          profile {\n            author {\n              id\n            }\n            avatar\n            username\n          }\n        }\n      }\n    }\n  }\n": types.GetDappListDocument,
    "\n  mutation CreateZucityDappMutation($input: CreateZucityDappInfoInput!) {\n    createZucityDappInfo(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": types.CreateZucityDappMutationDocument,
    "\n  mutation UpdateZucityDappMutation($input: UpdateZucityDappInfoInput!) {\n    updateZucityDappInfo(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": types.UpdateZucityDappMutationDocument,
    "\n  query GetDappById($id: ID!) {\n    node(id: $id) {\n      ... on ZucityDappInfo {\n        id\n        appName\n        tagline\n        developerName\n        description\n        bannerUrl\n        categories\n        devStatus\n        openSource\n        repositoryUrl\n        appUrl\n        websiteUrl\n        docsUrl\n        isInstallable\n        appLogoUrl\n        auditLogUrl\n        isSCApp\n        scAddresses {\n          address\n          chain\n        }\n        profile {\n          author {\n            id\n          }\n          avatar\n          username\n        }\n      }\n    }\n  }\n": types.GetDappByIdDocument,
    "\n  query GetAllEvents($first: Int) {\n    zucityEventIndex(first: $first) {\n      edges {\n        node {\n          id\n          description\n          profileId\n          tagline\n          customAttributes {\n            tbd\n          }\n          gated\n          superAdmin {\n            id\n          }\n          admins {\n            id\n          }\n          author {\n            id\n          }\n          customLinks {\n            links\n            title\n          }\n          createdAt\n          endTime\n          externalUrl\n          imageUrl\n          members {\n            id\n          }\n          participantCount\n          spaceId\n          startTime\n          status\n          supportChain\n          timezone\n          title\n          tracks\n        }\n      }\n    }\n  }\n": types.GetAllEventsDocument,
    "\n  query GetEventByIds($ids: [ID!]!) {\n    nodes(ids: $ids) {\n      ... on ZucityEvent {\n        id\n        description\n        profileId\n        tagline\n        customAttributes {\n          tbd\n        }\n        gated\n        superAdmin {\n          id\n        }\n        admins {\n          id\n        }\n        author {\n          id\n        }\n        customLinks {\n          links\n          title\n        }\n        createdAt\n        endTime\n        externalUrl\n        imageUrl\n        members {\n          id\n        }\n        participantCount\n        spaceId\n        startTime\n        status\n        supportChain\n        timezone\n        title\n        tracks\n      }\n    }\n  }\n": types.GetEventByIdsDocument,
    "\n  query SearchProfileByExactUsername($username: String!) {\n    zucityProfileIndex(\n      first: 20\n      filters: { where: { username: { equalTo: $username } } }\n    ) {\n      edges {\n        node {\n          id\n          username\n          avatar\n          author {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.SearchProfileByExactUsernameDocument,
    "\n  query GetProfileByDID($did: ID!) {\n    node(id: $did) {\n      ... on CeramicAccount {\n        zucityProfile {\n          id\n          username\n          avatar\n          author {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetProfileByDidDocument,
    "\n  mutation CreateProfile($input: SetZucityProfileInput!) {\n    setZucityProfile(input: $input) {\n      document {\n        id\n        username\n      }\n    }\n  }\n": types.CreateProfileDocument,
    "\n  query GetOwnProfile {\n    viewer {\n      zucityProfile {\n        author {\n          id\n        }\n        avatar\n        id\n        username\n      }\n    }\n  }\n": types.GetOwnProfileDocument,
    "\n  query GetUserOwnSpace($did: ID!) {\n    node(id: $did) {\n      ... on CeramicAccount {\n        zucityProfile {\n          id\n          username\n          avatar\n          author {\n            id\n          }\n          spaces(first: 100) {\n            edges {\n              node {\n                id\n                author {\n                  id\n                }\n                avatar\n                banner\n                name\n                description\n                category\n                color\n                profileId\n                customAttributes {\n                  tbd\n                }\n                customLinks {\n                  links\n                  title\n                }\n                owner {\n                  id\n                }\n                socialLinks {\n                  links\n                  title\n                }\n                tagline\n                tags {\n                  tag\n                }\n                createdAt\n                updatedAt\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetUserOwnSpaceDocument,
    "\n  query GetUserOwnEvent($did: ID!) {\n    node(id: $did) {\n      ... on CeramicAccount {\n        zucityProfile {\n          id\n          username\n          avatar\n          events(first: 100) {\n            edges {\n              node {\n                id\n                admins {\n                  id\n                }\n                createdAt\n                author {\n                  id\n                }\n                customAttributes {\n                  tbd\n                }\n                customLinks {\n                  links\n                  title\n                }\n                description\n                endTime\n                externalUrl\n                gated\n                imageUrl\n                members {\n                  id\n                }\n                participantCount\n                minParticipant\n                profileId\n                spaceId\n                startTime\n                status\n                superAdmin {\n                  id\n                }\n                supportChain\n                tagline\n                timezone\n                title\n                tracks\n              }\n            }\n          }\n          author {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetUserOwnEventDocument,
    "\n  query GetMembers($source: String, $resourceId: String) {\n    zucityUserRolesIndex(\n      first: 1000\n      filters: {\n        where: {\n          source: { equalTo: $source }\n          resourceId: { equalTo: $resourceId }\n        }\n      }\n    ) {\n      edges {\n        node {\n          roleId\n          customAttributes {\n            tbd\n          }\n          userId {\n            zucityProfile {\n              avatar\n              username\n              author {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetMembersDocument,
    "\n  query GetUserRole($userId: String, $resourceId: String, $resource: String) {\n    zucityUserRolesIndex(\n      first: 1\n      filters: {\n        where: {\n          userId: { equalTo: $userId }\n          resourceId: { equalTo: $resourceId }\n          source: { equalTo: $resource }\n        }\n      }\n    ) {\n      edges {\n        node {\n          id\n          roleId\n          userId {\n            zucityProfile {\n              avatar\n              author {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetUserRoleDocument,
    "\n  mutation CreateZucityUserRoles($input: CreateZucityUserRolesInput!) {\n    createZucityUserRoles(input: $input) {\n      document {\n        userId {\n          id\n        }\n        created_at\n        updated_at\n        resourceId\n        source\n        roleId\n      }\n    }\n  }\n": types.CreateZucityUserRolesDocument,
    "\n  mutation enableIndexingZucityUserRoles(\n    $input: EnableIndexingZucityUserRolesInput!\n  ) {\n    enableIndexingZucityUserRoles(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": types.EnableIndexingZucityUserRolesDocument,
    "\n  mutation UpdateZucityUserRoles($input: UpdateZucityUserRolesInput!) {\n    updateZucityUserRoles(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": types.UpdateZucityUserRolesDocument,
    "\n  query GetUserRoles($userId: String) {\n    zucityUserRolesIndex(\n      first: 1000\n      filters: { where: { userId: { equalTo: $userId } } }\n    ) {\n      edges {\n        node {\n          id\n          roleId\n          resourceId\n          source\n          userId {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetUserRolesDocument,
    "\n  query GetSpace($id: ID!) {\n    node(id: $id) {\n      ... on ZucitySpace {\n        id\n        avatar\n        banner\n        description\n        name\n        profileId\n        tagline\n        category\n        color\n        createdAt\n        updatedAt\n        gated\n        tags {\n          tag\n        }\n        customAttributes {\n          tbd\n        }\n        socialLinks {\n          title\n          links\n        }\n        customLinks {\n          title\n          links\n        }\n        owner {\n          id\n          zucityProfile {\n            id\n            avatar\n            author {\n              id\n            }\n            username\n          }\n        }\n        announcements(first: 100) {\n          edges {\n            node {\n              id\n              createdAt\n            }\n          }\n        }\n        installedApps(first: 100) {\n          edges {\n            node {\n              id\n              sourceId\n              spaceId\n              nativeAppName\n              installedAppId\n              createdAt\n              updatedAt\n              installedApp {\n                id\n                appName\n                appType\n                description\n                tagline\n                bannerUrl\n                appUrl\n                openSource\n                devStatus\n                developerName\n                categories\n                appLogoUrl\n              }\n            }\n          }\n        }\n        spaceGating(first: 100) {\n          edges {\n            node {\n              id\n              poapsId {\n                poapId\n              }\n              zuPassInfo {\n                registration\n                eventId\n                eventName\n              }\n              gatingStatus\n              spaceId\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetSpaceDocument,
    "\n  query GetSpaceByIds($ids: [ID!]!) {\n    nodes(ids: $ids) {\n      ... on ZucitySpace {\n        id\n        avatar\n        banner\n        description\n        name\n        profileId\n        tagline\n        category\n        color\n        createdAt\n        updatedAt\n        tags {\n          tag\n        }\n        customAttributes {\n          tbd\n        }\n        socialLinks {\n          title\n          links\n        }\n        customLinks {\n          title\n          links\n        }\n        owner {\n          id\n          zucityProfile {\n            id\n            avatar\n            author {\n              id\n            }\n            username\n          }\n        }\n      }\n    }\n  }\n": types.GetSpaceByIdsDocument,
    "\n  mutation InstallDappToSpace($input: CreateZucityInstalledAppInput!) {\n    createZucityInstalledApp(input: $input) {\n      document {\n        id\n        sourceId\n        spaceId\n        nativeAppName\n        installedAppId\n        installedApp {\n          id\n          appName\n        }\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": types.InstallDappToSpaceDocument,
    "\n  query GetSpaceInstalledApps(\n    $filters: ZucityInstalledAppFiltersInput\n    $first: Int\n    $after: String\n  ) {\n    zucityInstalledAppIndex(filters: $filters, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          sourceId\n          spaceId\n          nativeAppName\n          installedAppId\n          createdAt\n          updatedAt\n          installedApp {\n            id\n            appName\n            appType\n            description\n            tagline\n            bannerUrl\n            appUrl\n            openSource\n            devStatus\n            developerName\n            categories\n            appLogoUrl\n          }\n          space {\n            id\n            name\n          }\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": types.GetSpaceInstalledAppsDocument,
    "\n  mutation UninstallDappFromSpace(\n    $input: EnableIndexingZucityInstalledAppInput!\n  ) {\n    enableIndexingZucityInstalledApp(input: $input) {\n      document {\n        id\n        sourceId\n        spaceId\n        installedAppId\n        installedApp {\n          id\n          appName\n        }\n        createdAt\n        updatedAt\n      }\n    }\n  }\n": types.UninstallDappFromSpaceDocument,
    "\n  mutation createZucitySpaceMutation($input: CreateZucitySpaceInput!) {\n    createZucitySpace(input: $input) {\n      document {\n        id\n        name\n        description\n        profileId\n        avatar\n        banner\n        category\n      }\n    }\n  }\n": types.CreateZucitySpaceMutationDocument,
    "\n  query GetSpaces($first: Int) {\n    zucitySpaceIndex(first: $first) {\n      edges {\n        node {\n          id\n          avatar\n          banner\n          description\n          name\n          profileId\n          tagline\n          category\n          color\n          createdAt\n          updatedAt\n          tags {\n            tag\n          }\n          customAttributes {\n            tbd\n          }\n          socialLinks {\n            title\n            links\n          }\n          customLinks {\n            title\n            links\n          }\n          owner {\n            id\n            zucityProfile {\n              id\n              avatar\n              author {\n                id\n              }\n              username\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetSpacesDocument,
    "\n  query GetSpaceAndEvents(\n    $id: ID!\n    $userRolesFirst: Int = 100\n    $userRolesFilters: ZucityUserRolesFiltersInput\n  ) {\n    node(id: $id) {\n      ... on ZucitySpace {\n        id\n        avatar\n        banner\n        description\n        name\n        profileId\n        tagline\n        category\n        color\n        createdAt\n        updatedAt\n        gated\n        tags {\n          tag\n        }\n        customAttributes {\n          tbd\n        }\n        socialLinks {\n          title\n          links\n        }\n        customLinks {\n          title\n          links\n        }\n        owner {\n          id\n          zucityProfile {\n            id\n            avatar\n            author {\n              id\n            }\n            username\n          }\n        }\n        events(first: 100) {\n          edges {\n            node {\n              createdAt\n              description\n              endTime\n              externalUrl\n              gated\n              id\n              imageUrl\n              maxParticipant\n              meetingUrl\n              minParticipant\n              participantCount\n              profileId\n              spaceId\n              startTime\n              status\n              tagline\n              timezone\n              title\n              space {\n                name\n                avatar\n              }\n            }\n          }\n        }\n        userRoles(filters: $userRolesFilters, first: $userRolesFirst) {\n          edges {\n            node {\n              roleId\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetSpaceAndEventsDocument,
    "\n  query GetSpacesAndMembers(\n    $first: Int\n    $userRolesFirst: Int = 100\n    $userRolesFilters: ZucityUserRolesFiltersInput\n  ) {\n    zucitySpaceIndex(first: $first) {\n      edges {\n        node {\n          id\n          avatar\n          banner\n          description\n          name\n          profileId\n          tagline\n          category\n          color\n          createdAt\n          updatedAt\n          tags {\n            tag\n          }\n          customAttributes {\n            tbd\n          }\n          socialLinks {\n            title\n            links\n          }\n          customLinks {\n            title\n            links\n          }\n          owner {\n            id\n            zucityProfile {\n              id\n              avatar\n              author {\n                id\n              }\n              username\n            }\n          }\n          userRoles(filters: $userRolesFilters, first: $userRolesFirst) {\n            edges {\n              node {\n                roleId\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetSpacesAndMembersDocument,
    "\n  mutation UpdateZucitySpace($input: UpdateZucitySpaceInput!) {\n    updateZucitySpace(input: $input) {\n      document {\n        id\n        name\n        description\n        avatar\n        banner\n        category\n      }\n    }\n  }\n": types.UpdateZucitySpaceDocument,
    "\n  mutation CreateSpaceGatingRule($input: CreateZucitySpaceGatingInput!) {\n    createZucitySpaceGating(input: $input) {\n      document {\n        id\n        spaceId\n        poapsId {\n          poapId\n        }\n        zuPassInfo {\n          registration\n          eventId\n          eventName\n        }\n      }\n    } \n  }\n": types.CreateSpaceGatingRuleDocument,
    "\n  mutation UpdateSpaceGatingRule($input: UpdateZucitySpaceGatingInput!) {\n    updateZucitySpaceGating(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": types.UpdateSpaceGatingRuleDocument,
    "\n  mutation DeleteSpaceGatingRule($input: EnableIndexingZucitySpaceGatingInput!) {\n    enableIndexingZucitySpaceGating(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n": types.DeleteSpaceGatingRuleDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateZucityAnnouncementMutation(\n    $input: CreateZucityAnnouncementInput!\n  ) {\n    createZucityAnnouncement(input: $input) {\n      document {\n        id\n        title\n        description\n        createdAt\n        updatedAt\n        sourceId\n        spaceId\n        eventId\n        space {\n          id\n          name\n        }\n        event {\n          id\n          title\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').CreateZucityAnnouncementMutationDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateZucityAnnouncementMutation(\n    $input: UpdateZucityAnnouncementInput!\n  ) {\n    updateZucityAnnouncement(input: $input) {\n      document {\n        id\n        title\n        description\n        updatedAt\n      }\n    }\n  }\n"): typeof import('./graphql').UpdateZucityAnnouncementMutationDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation EnableIndexingZucityAnnouncement(\n    $input: EnableIndexingZucityAnnouncementInput!\n  ) {\n    enableIndexingZucityAnnouncement(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n"): typeof import('./graphql').EnableIndexingZucityAnnouncementDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSpaceAnnouncements($id: ID!, $first: Int = 100) {\n    node(id: $id) {\n      ... on ZucitySpace {\n        announcements(first: $first) {\n          edges {\n            node {\n              id\n              title\n              tags {\n                tag\n              }\n              description\n              createdAt\n              updatedAt\n              sourceId\n              author {\n                id\n                zucityProfile {\n                  avatar\n                  username\n                }\n              }\n            }\n          }\n          pageInfo {\n            hasNextPage\n            endCursor\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetSpaceAnnouncementsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetEventAnnouncements($id: ID!, $first: Int = 100) {\n    node(id: $id) {\n      ... on ZucityEvent {\n        announcements(first: $first) {\n          edges {\n            node {\n              id\n              title\n              tags {\n                tag\n              }\n              description\n              createdAt\n              updatedAt\n              sourceId\n              author {\n                id\n                zucityProfile {\n                  avatar\n                  username\n                }\n              }\n            }\n          }\n          pageInfo {\n            hasNextPage\n            endCursor\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetEventAnnouncementsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDappList($first: Int = 100, $filters: ZucityDappInfoFiltersInput) {\n    zucityDappInfoIndex(first: $first, filters: $filters) {\n      edges {\n        node {\n          id\n          appName\n          tagline\n          developerName\n          description\n          bannerUrl\n          categories\n          devStatus\n          openSource\n          repositoryUrl\n          appUrl\n          websiteUrl\n          docsUrl\n          isInstallable\n          appLogoUrl\n          auditLogUrl\n          isSCApp\n          scAddresses {\n            address\n            chain\n          }\n          profile {\n            author {\n              id\n            }\n            avatar\n            username\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetDappListDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateZucityDappMutation($input: CreateZucityDappInfoInput!) {\n    createZucityDappInfo(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n"): typeof import('./graphql').CreateZucityDappMutationDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateZucityDappMutation($input: UpdateZucityDappInfoInput!) {\n    updateZucityDappInfo(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n"): typeof import('./graphql').UpdateZucityDappMutationDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDappById($id: ID!) {\n    node(id: $id) {\n      ... on ZucityDappInfo {\n        id\n        appName\n        tagline\n        developerName\n        description\n        bannerUrl\n        categories\n        devStatus\n        openSource\n        repositoryUrl\n        appUrl\n        websiteUrl\n        docsUrl\n        isInstallable\n        appLogoUrl\n        auditLogUrl\n        isSCApp\n        scAddresses {\n          address\n          chain\n        }\n        profile {\n          author {\n            id\n          }\n          avatar\n          username\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetDappByIdDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAllEvents($first: Int) {\n    zucityEventIndex(first: $first) {\n      edges {\n        node {\n          id\n          description\n          profileId\n          tagline\n          customAttributes {\n            tbd\n          }\n          gated\n          superAdmin {\n            id\n          }\n          admins {\n            id\n          }\n          author {\n            id\n          }\n          customLinks {\n            links\n            title\n          }\n          createdAt\n          endTime\n          externalUrl\n          imageUrl\n          members {\n            id\n          }\n          participantCount\n          spaceId\n          startTime\n          status\n          supportChain\n          timezone\n          title\n          tracks\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetAllEventsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetEventByIds($ids: [ID!]!) {\n    nodes(ids: $ids) {\n      ... on ZucityEvent {\n        id\n        description\n        profileId\n        tagline\n        customAttributes {\n          tbd\n        }\n        gated\n        superAdmin {\n          id\n        }\n        admins {\n          id\n        }\n        author {\n          id\n        }\n        customLinks {\n          links\n          title\n        }\n        createdAt\n        endTime\n        externalUrl\n        imageUrl\n        members {\n          id\n        }\n        participantCount\n        spaceId\n        startTime\n        status\n        supportChain\n        timezone\n        title\n        tracks\n      }\n    }\n  }\n"): typeof import('./graphql').GetEventByIdsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SearchProfileByExactUsername($username: String!) {\n    zucityProfileIndex(\n      first: 20\n      filters: { where: { username: { equalTo: $username } } }\n    ) {\n      edges {\n        node {\n          id\n          username\n          avatar\n          author {\n            id\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').SearchProfileByExactUsernameDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProfileByDID($did: ID!) {\n    node(id: $did) {\n      ... on CeramicAccount {\n        zucityProfile {\n          id\n          username\n          avatar\n          author {\n            id\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetProfileByDidDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateProfile($input: SetZucityProfileInput!) {\n    setZucityProfile(input: $input) {\n      document {\n        id\n        username\n      }\n    }\n  }\n"): typeof import('./graphql').CreateProfileDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetOwnProfile {\n    viewer {\n      zucityProfile {\n        author {\n          id\n        }\n        avatar\n        id\n        username\n      }\n    }\n  }\n"): typeof import('./graphql').GetOwnProfileDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUserOwnSpace($did: ID!) {\n    node(id: $did) {\n      ... on CeramicAccount {\n        zucityProfile {\n          id\n          username\n          avatar\n          author {\n            id\n          }\n          spaces(first: 100) {\n            edges {\n              node {\n                id\n                author {\n                  id\n                }\n                avatar\n                banner\n                name\n                description\n                category\n                color\n                profileId\n                customAttributes {\n                  tbd\n                }\n                customLinks {\n                  links\n                  title\n                }\n                owner {\n                  id\n                }\n                socialLinks {\n                  links\n                  title\n                }\n                tagline\n                tags {\n                  tag\n                }\n                createdAt\n                updatedAt\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetUserOwnSpaceDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUserOwnEvent($did: ID!) {\n    node(id: $did) {\n      ... on CeramicAccount {\n        zucityProfile {\n          id\n          username\n          avatar\n          events(first: 100) {\n            edges {\n              node {\n                id\n                admins {\n                  id\n                }\n                createdAt\n                author {\n                  id\n                }\n                customAttributes {\n                  tbd\n                }\n                customLinks {\n                  links\n                  title\n                }\n                description\n                endTime\n                externalUrl\n                gated\n                imageUrl\n                members {\n                  id\n                }\n                participantCount\n                minParticipant\n                profileId\n                spaceId\n                startTime\n                status\n                superAdmin {\n                  id\n                }\n                supportChain\n                tagline\n                timezone\n                title\n                tracks\n              }\n            }\n          }\n          author {\n            id\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetUserOwnEventDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetMembers($source: String, $resourceId: String) {\n    zucityUserRolesIndex(\n      first: 1000\n      filters: {\n        where: {\n          source: { equalTo: $source }\n          resourceId: { equalTo: $resourceId }\n        }\n      }\n    ) {\n      edges {\n        node {\n          roleId\n          customAttributes {\n            tbd\n          }\n          userId {\n            zucityProfile {\n              avatar\n              username\n              author {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetMembersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUserRole($userId: String, $resourceId: String, $resource: String) {\n    zucityUserRolesIndex(\n      first: 1\n      filters: {\n        where: {\n          userId: { equalTo: $userId }\n          resourceId: { equalTo: $resourceId }\n          source: { equalTo: $resource }\n        }\n      }\n    ) {\n      edges {\n        node {\n          id\n          roleId\n          userId {\n            zucityProfile {\n              avatar\n              author {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetUserRoleDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateZucityUserRoles($input: CreateZucityUserRolesInput!) {\n    createZucityUserRoles(input: $input) {\n      document {\n        userId {\n          id\n        }\n        created_at\n        updated_at\n        resourceId\n        source\n        roleId\n      }\n    }\n  }\n"): typeof import('./graphql').CreateZucityUserRolesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation enableIndexingZucityUserRoles(\n    $input: EnableIndexingZucityUserRolesInput!\n  ) {\n    enableIndexingZucityUserRoles(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n"): typeof import('./graphql').EnableIndexingZucityUserRolesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateZucityUserRoles($input: UpdateZucityUserRolesInput!) {\n    updateZucityUserRoles(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n"): typeof import('./graphql').UpdateZucityUserRolesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUserRoles($userId: String) {\n    zucityUserRolesIndex(\n      first: 1000\n      filters: { where: { userId: { equalTo: $userId } } }\n    ) {\n      edges {\n        node {\n          id\n          roleId\n          resourceId\n          source\n          userId {\n            id\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetUserRolesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSpace($id: ID!) {\n    node(id: $id) {\n      ... on ZucitySpace {\n        id\n        avatar\n        banner\n        description\n        name\n        profileId\n        tagline\n        category\n        color\n        createdAt\n        updatedAt\n        gated\n        tags {\n          tag\n        }\n        customAttributes {\n          tbd\n        }\n        socialLinks {\n          title\n          links\n        }\n        customLinks {\n          title\n          links\n        }\n        owner {\n          id\n          zucityProfile {\n            id\n            avatar\n            author {\n              id\n            }\n            username\n          }\n        }\n        announcements(first: 100) {\n          edges {\n            node {\n              id\n              createdAt\n            }\n          }\n        }\n        installedApps(first: 100) {\n          edges {\n            node {\n              id\n              sourceId\n              spaceId\n              nativeAppName\n              installedAppId\n              createdAt\n              updatedAt\n              installedApp {\n                id\n                appName\n                appType\n                description\n                tagline\n                bannerUrl\n                appUrl\n                openSource\n                devStatus\n                developerName\n                categories\n                appLogoUrl\n              }\n            }\n          }\n        }\n        spaceGating(first: 100) {\n          edges {\n            node {\n              id\n              poapsId {\n                poapId\n              }\n              zuPassInfo {\n                registration\n                eventId\n                eventName\n              }\n              gatingStatus\n              spaceId\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetSpaceDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSpaceByIds($ids: [ID!]!) {\n    nodes(ids: $ids) {\n      ... on ZucitySpace {\n        id\n        avatar\n        banner\n        description\n        name\n        profileId\n        tagline\n        category\n        color\n        createdAt\n        updatedAt\n        tags {\n          tag\n        }\n        customAttributes {\n          tbd\n        }\n        socialLinks {\n          title\n          links\n        }\n        customLinks {\n          title\n          links\n        }\n        owner {\n          id\n          zucityProfile {\n            id\n            avatar\n            author {\n              id\n            }\n            username\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetSpaceByIdsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation InstallDappToSpace($input: CreateZucityInstalledAppInput!) {\n    createZucityInstalledApp(input: $input) {\n      document {\n        id\n        sourceId\n        spaceId\n        nativeAppName\n        installedAppId\n        installedApp {\n          id\n          appName\n        }\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"): typeof import('./graphql').InstallDappToSpaceDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSpaceInstalledApps(\n    $filters: ZucityInstalledAppFiltersInput\n    $first: Int\n    $after: String\n  ) {\n    zucityInstalledAppIndex(filters: $filters, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          sourceId\n          spaceId\n          nativeAppName\n          installedAppId\n          createdAt\n          updatedAt\n          installedApp {\n            id\n            appName\n            appType\n            description\n            tagline\n            bannerUrl\n            appUrl\n            openSource\n            devStatus\n            developerName\n            categories\n            appLogoUrl\n          }\n          space {\n            id\n            name\n          }\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"): typeof import('./graphql').GetSpaceInstalledAppsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UninstallDappFromSpace(\n    $input: EnableIndexingZucityInstalledAppInput!\n  ) {\n    enableIndexingZucityInstalledApp(input: $input) {\n      document {\n        id\n        sourceId\n        spaceId\n        installedAppId\n        installedApp {\n          id\n          appName\n        }\n        createdAt\n        updatedAt\n      }\n    }\n  }\n"): typeof import('./graphql').UninstallDappFromSpaceDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createZucitySpaceMutation($input: CreateZucitySpaceInput!) {\n    createZucitySpace(input: $input) {\n      document {\n        id\n        name\n        description\n        profileId\n        avatar\n        banner\n        category\n      }\n    }\n  }\n"): typeof import('./graphql').CreateZucitySpaceMutationDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSpaces($first: Int) {\n    zucitySpaceIndex(first: $first) {\n      edges {\n        node {\n          id\n          avatar\n          banner\n          description\n          name\n          profileId\n          tagline\n          category\n          color\n          createdAt\n          updatedAt\n          tags {\n            tag\n          }\n          customAttributes {\n            tbd\n          }\n          socialLinks {\n            title\n            links\n          }\n          customLinks {\n            title\n            links\n          }\n          owner {\n            id\n            zucityProfile {\n              id\n              avatar\n              author {\n                id\n              }\n              username\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetSpacesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSpaceAndEvents(\n    $id: ID!\n    $userRolesFirst: Int = 100\n    $userRolesFilters: ZucityUserRolesFiltersInput\n  ) {\n    node(id: $id) {\n      ... on ZucitySpace {\n        id\n        avatar\n        banner\n        description\n        name\n        profileId\n        tagline\n        category\n        color\n        createdAt\n        updatedAt\n        gated\n        tags {\n          tag\n        }\n        customAttributes {\n          tbd\n        }\n        socialLinks {\n          title\n          links\n        }\n        customLinks {\n          title\n          links\n        }\n        owner {\n          id\n          zucityProfile {\n            id\n            avatar\n            author {\n              id\n            }\n            username\n          }\n        }\n        events(first: 100) {\n          edges {\n            node {\n              createdAt\n              description\n              endTime\n              externalUrl\n              gated\n              id\n              imageUrl\n              maxParticipant\n              meetingUrl\n              minParticipant\n              participantCount\n              profileId\n              spaceId\n              startTime\n              status\n              tagline\n              timezone\n              title\n              space {\n                name\n                avatar\n              }\n            }\n          }\n        }\n        userRoles(filters: $userRolesFilters, first: $userRolesFirst) {\n          edges {\n            node {\n              roleId\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetSpaceAndEventsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSpacesAndMembers(\n    $first: Int\n    $userRolesFirst: Int = 100\n    $userRolesFilters: ZucityUserRolesFiltersInput\n  ) {\n    zucitySpaceIndex(first: $first) {\n      edges {\n        node {\n          id\n          avatar\n          banner\n          description\n          name\n          profileId\n          tagline\n          category\n          color\n          createdAt\n          updatedAt\n          tags {\n            tag\n          }\n          customAttributes {\n            tbd\n          }\n          socialLinks {\n            title\n            links\n          }\n          customLinks {\n            title\n            links\n          }\n          owner {\n            id\n            zucityProfile {\n              id\n              avatar\n              author {\n                id\n              }\n              username\n            }\n          }\n          userRoles(filters: $userRolesFilters, first: $userRolesFirst) {\n            edges {\n              node {\n                roleId\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetSpacesAndMembersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateZucitySpace($input: UpdateZucitySpaceInput!) {\n    updateZucitySpace(input: $input) {\n      document {\n        id\n        name\n        description\n        avatar\n        banner\n        category\n      }\n    }\n  }\n"): typeof import('./graphql').UpdateZucitySpaceDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateSpaceGatingRule($input: CreateZucitySpaceGatingInput!) {\n    createZucitySpaceGating(input: $input) {\n      document {\n        id\n        spaceId\n        poapsId {\n          poapId\n        }\n        zuPassInfo {\n          registration\n          eventId\n          eventName\n        }\n      }\n    } \n  }\n"): typeof import('./graphql').CreateSpaceGatingRuleDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateSpaceGatingRule($input: UpdateZucitySpaceGatingInput!) {\n    updateZucitySpaceGating(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n"): typeof import('./graphql').UpdateSpaceGatingRuleDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteSpaceGatingRule($input: EnableIndexingZucitySpaceGatingInput!) {\n    enableIndexingZucitySpaceGating(input: $input) {\n      document {\n        id\n      }\n    }\n  }\n"): typeof import('./graphql').DeleteSpaceGatingRuleDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
